### ISSUE TITLE
Is this bug fixed?

### ISSUE THREAD

**Issue by beyondbright** [PaulWoitaschek/RoomMultiModuleBug#1]
Hi, I have this issues too, was this fixed?

**Comment by PaulWoitaschek** [comment]
Yes, in 1.1.0-alpha03. Check the issue link in the readme.

**Comment by beyondbright** [comment]
Hi, I have used "1.1.0-alpha3" but the problem still happened. When I builded the project, there showed some error like this:

错误: Each bind variable in the query must have a matching method parameter. Cannot find method parameters for :userIds.
错误: Unused parameter: arg0
错误: Each bind variable in the query must have a matching method parameter. Cannot find method parameters for :first, :last.
错误: Unused parameters: arg0,arg1
4 个错误

Here is my project https://github.com/beyondbright/AndroidArchitectureSample

Did I miss something? Please help me. Thanks.

**Comment by PaulWoitaschek** [comment]
Let's use the original issue for discussing this.
